level_5_projects/my_project/main_app/urls.py
from django.urls import path
from main_app import views



app_name = 'main_app'

urlpatterns = [
    path('registration/', views.register, name='registration'),
    path('user_login/', views.user_login, name='user_login'),
]

level_5_projects/my_project/my_project/urls.py
from django.contrib import admin
from django.urls import path, include
from main_app import views


urlpatterns = [
    path('', views.index, name='index'),
    path('admin/', admin.site.urls),
    path('main_app/', include('main_app.urls')),
    path('logout/', views.user_logout, name='logout'),
    path('special/', views.special, name='special'),
]

level_5_projects/my_project/main_app/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class UserProfileInfo(models.Model):

    user = models.OneToOneField(User, on_delete=models.CASCADE)

    portfolio_site = models.URLField(blank=True)
    profile_picture = models.ImageField(upload_to='profile_pick', blank=True)

    def __str__(self):
        return self.user.username

level_5_projects/my_project/main_app/forms.py
from django import forms
from django.contrib.auth.models import User
from main_app.models import UserProfileInfo

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta():
        model = User
        fields = ('username', 'email', 'password')

class UserProfileInfoForm(forms.ModelForm):
    class Meta():
        model = UserProfileInfo
        fields = ('portfolio_site', 'profile_picture')

level_5_projects/my_project/main_app/views.py
from django.shortcuts import render
from main_app.forms import UserForm, UserProfileInfoForm

#
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.contrib.auth.decorators import login_required


# Create your views here.
def index(request):
    return render(request, 'main_app/index.html')

@login_required
def special(request):
    return HttpResponse('You are logged in, Nice!')

@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))


def register(request):
    if request.user.is_authenticated:
        return HttpResponse("You are Logined")
    else:
        registered = False

        if request.method == "POST":
            user_form = UserForm(data=request.POST)
            profile_form = UserProfileInfoForm(data=request.POST)

            if user_form.is_valid() and profile_form.is_valid():

                user = user_form.save()
                user.set_password(user.password)
                user.save()

                profile = profile_form.save(commit=False)
                profile.user = user

                if 'profile_picture' in request.FILES:
                    profile.profile_picture = request.FILES['profile_picture']

                profile.save()

                registered = True
            else:
                print(user_form.errors, profile_form.errors)
        else:
            user_form = UserForm()
            profile_form = UserProfileInfoForm()

        return render(request, 'main_app/registration.html',
                      {'user_form':user_form,
                       'profile_form':profile_form,
                       'registered':registered})

def user_login(request):

    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username, password=password)

        if user:
            if user.is_active:
                login(request, user)
                return HttpResponseRedirect(reverse('index'))

            else:
                return HttpResponse('ACCOUNT NOT ACTIVE')

        else:
            print('Someone tried to login and failed!')
            print(f'Username: {username} and password {password}')
            return HttpResponse('invalid login details supplied')
    else:
        return render(request, 'main_app/login.html', {})

level_5_projects/my_project/templates/main_app/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title></title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
    integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
</head>
<body>
  <div class="container">
    <nav class="navbar navbar-expand-lg bg-body-tertiary">
      <div class="container">
        <div class="container-fluid">
          <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'index' %}">Home</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" aria-current="page" href="{% url 'admin:index' %}">Admin</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" aria-current="page" href="{% url 'main_app:registration' %}">Register</a>
              </li>

              {% if user.is_authenticated %}
                <li class="nav-item">
                  <a class="nav-link" aria-current="page" href="{% url 'logout' %}">Logout</a>
                </li>
              {% else %}
                <li class="nav-item">
                  <a class="nav-link" aria-current="page" href="{% url 'main_app:user_login' %}">Login</a>
                </li>
              {% endif %}
            </ul>
          </div>
        </div>
      </div>
    </nav>
  </div>
  <h1></h1>
  <div class="container">
    {% block body_block %}
    {% endblock %}
  </div>
</body>
</html>

level_5_projects/my_project/templates/main_app/index.html
{% extends "main_app/base.html" %}
{% block body_block %}

<div class="jumbotron">
  <h1>Django Level Five</h1>
</div>

{% endblock %}

level_5_projects/my_project/templates/main_app/login.html
{% extends "main_app/base.html" %}
{% block body_block %}

<div class="jumbotron">
  <h1>Please Login</h1>
  <form action="{% url 'main_app:user_login' %}" method="post">
    {% csrf_token %}
    <label for="username">Username:</label>
    <input type="text" name="username" placeholder="Enter Username">

    <label for="password">Password</label>
    <input type="password" name="password">

    <input type="submit" name="" value="Login">
  </form>

</div>

{% endblock %}

level_5_projects/my_project/templates/main_app/registration.html
{% extends 'main_app/base.html' %}
{% load static %}

{% block body_block %}

<div class="jumbotron">
  {% if registered %}
    <h1>Thanks you for registration</h1>
  {% else %}
    <h1>Register Here!</h1>
    <h3>Fill out the form:</h3>

    <form enctype="multipart/form-data" method="post">
      {% csrf_token %}
      {{ user_form.as_p }}
      {{ profile_form.as_p }}
      <input type="submit" name="" value="Register" href=''>
    </form>

  {% endif %}
</div>


{% endblock %}