advance_level_django_cbv/advance_level_django_cbv/urls.py
from django.contrib import admin
from django.urls import path, include
from base_app import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.IndexView.as_view()),
    path('base_app/', include('base_app.urls', namespace='base_app')),
]

advance_level_django_cbv/base_app/urls.py
from django.urls import path
from base_app import views

app_name = 'base_app'

urlpatterns = [
    path('', views.SchoolListView.as_view(), name='list'),
]

advance_level_django_cbv/base_app/models.py
from django.db import models

# Create your models here.
class School(models.Model):
    name = models.CharField(max_length=256)
    principal = models.CharField(max_length=256)
    location = models.CharField(max_length=256)

    def __str__(self):
        return self.name


class Student(models.Model):
    name = models.CharField(max_length=256)
    age = models.PositiveIntegerField()
    school = models.ForeignKey(School, related_name='students', on_delete=models.CASCADE)

    def __str__(self):
        return self.name

advance_level_django_cbv/base_app/views.py
from django.shortcuts import render
from django.views.generic import View, TemplateView, ListView, DetailView
from . import models

class IndexView(TemplateView):
    template_name = 'index.html'

class SchoolListView(ListView):
    context_object_name = 'schools'
    model = models.School
    # school_list (adding "_list")

class SchoolDetailView(DetailView):
    context_object_name = 'school_detail'
    model = models.School
    template_name = 'basic_app/school_detail.html'

advance_level_django_cbv/templates/base_app.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
    integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

    <title>Base</title>
</head>
<body>

    <nav class="navbar navbar-default navbar-static-top">
      <ul class="nav navbar-nav">
        <li><a class="navbar-brand" href="{% url 'base_app:list' %}">Schools</a></li>
        <li><a class="navbar-link" href="{% url 'admin:index' %}">Admin</a></li>
        <li><a class="" href="#"></a></li>
      </ul>
    </nav>


  <div class="container">
    {% block body_block %}
    {% endblock %}
  </div>
</body>
</html>

advance_level_django_cbv/templates/index.html
{% extends "base_app.html" %}
{% block body_block %}
  <div class="jumbotron">
    <h1>Home Page</h1>
  </div>
{% endblock %}